background = #28232F
foreground = #E9E1DC
background-opacity = 0.34
background-blur-radius = 24
cursor-color = #D8BF83
selection-background = #4B435A
selection-foreground = #FFF4EE
palette = 0=#28232F
palette = 1=#D58A91
palette = 2=#A8C69F
palette = 3=#D8BF83
palette = 4=#9FAFD1
palette = 5=#C2A0C7
palette = 6=#9BC4BC
palette = 7=#E9E1DC
palette = 8=#817A89
palette = 9=#E6A0A6
palette = 10=#BED8B6
palette = 11=#E8D29B
palette = 12=#B7C5E2
palette = 13=#D7B7DB
palette = 14=#B4D8D1
palette = 15=#FFF4EE

